Health-Education-England/hee-prototypes

app/assets/components/search/_search.scss

https://manifesto.atlassian.net/browse/HEE-317
Small tweak to fix alignment issues

tweaked search popup to align with library

---

app/assets/javascript/main.js
app/views/lks/maps.html

https://manifesto.atlassian.net/browse/HEE-319
Fixed links on map going to correct address, also fixed title
Added check on load so that if there is no SVG present the script will not try to run with a null (this might need further checking in the CMS as I'm not sure how it loads things)

Mapping component bug fixing

---

app/assets/components/search/_search.scss

Fixing bugs mentioned in https://github.com/Manifesto-Digital/hee-cms-platform/pull/99

fixing float issue with menu / search @ 641px

---

app/assets/components/tabs/README.md
app/assets/components/tabs/_tabs.scss
app/assets/components/tabs/macro.njk
app/assets/components/tabs/tabs.js
app/assets/components/tabs/template.njk
app/assets/javascript/main.js
app/assets/sass/main.scss
app/views/lks/content.html
docs/views/template.html

Pull request for tabs componet front, please ingnore the other branch feature/tabs

refactor from feature/tabs

---

app/assets/components/phase-banner/README.md
app/views/lks/lks-layout.html

adding html sample to readme
https://manifesto.atlassian.net/browse/HEE-261

added html example

---

app/assets/components/nav-map/_nav-map.scss
app/assets/components/nav-map/nav-map.js
app/assets/images/nav-maps/dental-regions.svg
app/assets/images/nav-maps/higher-regions.svg
app/assets/images/nav-maps/medical-regions.svg

Contains changes for https://manifesto.atlassian.net/browse/HEE-372 and https://manifesto.atlassian.net/browse/HEE-386

HEE-372 and HEE-386 Navigation map

---

app/assets/components/custom-header/template.njk
app/assets/components/lks-header/_header.scss
app/assets/components/submenu/submenu.js

Fixes keyboard selection and chevron alignment for the Nav bar
https://hee-tis.atlassian.net/browse/NWPS-810

NWPS-810 Drop down menu is not accessible

---

app/assets/components/cookies/cookies.js

https://hee-tis.atlassian.net/browse/NWPS-826

Added conditions to prevent errors, added refresh, fixed whitespace

---

app/assets/components/related-links-card/_related-links-card.scss
app/views/lks/content.html

https://hee-tis.atlassian.net/browse/NWPS-816
https://hee-tis.atlassian.net/browse/NWPS-820

NWPS-816 right hand card line height

---

app/assets/components/lks-header/_header.scss

Ready for review
https://hee-tis.atlassian.net/browse/NWPS-818

NWPS-818 header spacing

---

app/assets/components/custom-header/template.njk
app/assets/components/lks-header/_header.scss

https://hee-tis.atlassian.net/browse/NWPS-846

nwps 846 Header bug fixes

---

app/assets/components/tabs/README.md

Updating readme for https://github.com/Manifesto-Digital/hee-prototypes/pull/54/files / https://hee-tis.atlassian.net/browse/NWPS-777

Updated readme for NWPS-777

---

app/assets/components/cookies/cookies.js

https://hee-tis.atlassian.net/jira/software/c/projects/NWPS/boards/93?modal=detail&selectedIssue=NWPS-827

updated cookie status detection

---

app/assets/components/newsletter/README.md
app/assets/components/newsletter/newsletter.js
app/assets/javascript/main.js
app/views/lks/newsletter.html

This pull request adds JavaScript validation for the Newsletter subscribe form currently in PR https://github.com/Health-Education-England/hee-cms-platform/pull/196

Feature/NWPS-124 Added javascript validation for newsletter form

---

README.md

Have updated README to include build notes

NWPS-909 - Update readme with build note

---

package.json

- Updated node-sass to 7.0
- Ran npm update
- Excluded nhsuk-frontend version updating (kept at 4.1.0)

NWPS-899 NPM update and node-sass 7.0

---

app/views/includes/_globals.html
app/views/templates/blog-collection.html
app/views/templates/examples/blog-collection.html
app/views/templates/examples/publications-collection.html
dist/blocks/furniture/examples/page-microhero.html
dist/blocks/furniture/page-microhero.html
dist/inventory/index.html
dist/templates/404.html
dist/templates/az-listing.html
dist/templates/base-fullwidth.html
dist/templates/base-leftbar.html
dist/templates/base-rightbar.html
dist/templates/blog-collection.html
dist/templates/blog-item.html
dist/templates/examples/blog-collection.html
dist/templates/examples/publications-collection.html
dist/templates/homepage.html
dist/templates/index.html
dist/templates/mini-hub-item.html
dist/templates/news-collection.html
dist/templates/news-item.html
dist/templates/publications-collection.html
dist/templates/publications-item.html
dist/templates/publications-landing.html
dist/templates/search-listing.html
dist/templates/standard-content.html

- Implemented Blog collection overview page
- Created example template for Blog collection within prototype
- Change collection page example logic to use loop for items
- Updated status for Blog collection within globals include
FYI `dist/` directory can be ignored for review as this is just compiled assets generated by the pipeline.

NWPS-1230: Blog listings template

---

app/views/includes/_globals.html
app/views/templates/event-collection.html
app/views/templates/examples/event-collection.html
dist/inventory/index.html
dist/templates/404.html
dist/templates/az-listing.html
dist/templates/base-fullwidth.html
dist/templates/base-leftbar.html
dist/templates/base-rightbar.html
dist/templates/blog-item.html
dist/templates/event-collection.html
dist/templates/examples/event-collection.html
dist/templates/homepage.html
dist/templates/index.html
dist/templates/landing-page.html
dist/templates/mini-hub-item.html
dist/templates/news-collection.html
dist/templates/news-item.html
dist/templates/publications-collection.html
dist/templates/publications-item.html
dist/templates/publications-landing.html
dist/templates/standard-content.html

Added Event listings prototype page and example template

NWPS-1231: Event listings

---

app/views/alpha/third-a-mental-health.html
app/views/alpha/third-a-opportunity.html
app/views/alpha/third-b-opportunity.html
dist/alpha/third-a-mental-health.html
dist/alpha/third-a-opportunity.html
dist/alpha/third-b-opportunity.html

[NWPS-1482] Content changes on third navigation html files

---

app/views/templates/examples/publications-item.html
dist/templates/examples/publications-item.html

Contains amendment to add filesize to Downloads component on Publications item page.

NWPS-1460 - Publications item page Downloads card filesize

---

app/views/includes/_globals.html
app/views/templates/404.html
app/views/templates/examples/404.html
dist/inventory/index.html
dist/templates/404.html
dist/templates/az-listing.html
dist/templates/base-fullwidth.html
dist/templates/base-leftbar.html
dist/templates/base-rightbar.html
dist/templates/blog-item.html
dist/templates/examples/404.html
dist/templates/homepage.html
dist/templates/index.html
dist/templates/landing-page.html
dist/templates/mini-hub-item.html
dist/templates/news-collection.html
dist/templates/news-item.html
dist/templates/publications-collection.html
dist/templates/publications-item.html
dist/templates/publications-landing.html
dist/templates/search-listing.html
dist/templates/standard-content.html

@smanivasag here's the release branch for the 404 page :+1: 
Thanks :slightly_smiling_face:

Release: NWPS-1350 - 404 docs and example template

---

.github/workflows/build_test_deploy.yml

Update version of git-auto-commit-action
